### ISSUE TITLE
Deploy using vercel

### ISSUE THREAD

**Issue by bro-my-username-got-blocked** [whos-evan/elixir#6]
Any way to deploy using vercel?

**Comment by maverickteckh** [comment]
I would like to see this too.

**Comment by gamercoder69** [comment]
Not possible vercel is static websites

**Comment by ericksonbak52** [comment]
how would you host in on cycilic? is it possible

**Comment by Xoui** [comment]
Its somple

**Comment by Xoui** [comment]
Fork repo thwb logn cyclic with github
Then deploy the repo

**Comment by bro-my-username-got-blocked** [comment]
this is dumb, why did i make this
ofc you can't deploy using vercel
